ctrl-space-labs/gendox-core

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/model/dtos/criteria/DocumentCriteria.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/specifications/DocumentPredicates.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/SplitFileService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/UploadService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/utils/constants/QueryParamNames.java
> Feature 94 separate upload from split

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/authentication/AuthenticationService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/authentication/KeycloakAuthenticationService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/discord/utils/CommonCommandUtility.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/UserRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/UserService.java
- #127: As a backend developer, I want to create Keycloak's user, when discord user is created
- Add check if discord user has identifier, if not create identifier user.
> FIX #127 create Keycloak's user, when discord user is created

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/EmbeddingGroupRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentSectionService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/EmbeddingService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/SplitFileService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/TrainingService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/UploadService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSectionDTO.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSplitterProcessor.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSplitterReader.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSplitterWriter.java
- #120:
- #122:
- #130
- Fix the double split bug
- Implement the task, delete embeddings, embeddingGroup and sections when a document has updated
- update the save document file path
> FIX Tickets #120 #122 #130

- gendox-core-api/Dockerfile
- gendox-e2e-tests/Dockerfile
- Implement Docker Image with gendox-core-api and gendox-e2e-tests
- create Dockerfile for gendox-core-api
- create Dockerfile for gendox-e2e-tests
> FIX ticket #160

- docker-compose.yml
- gendox-core-api/src/main/resources/application-dev.yml
- gendox-core-api/src/main/resources/application-local.yml
- update docker-compose
- update application-dev.yml
- update application-local.yml
> FIX ticket #162

- .gitignore
- database/.gitignore
- database/src/main/resources/db/migrations/gendox-core/V20240117_102915__Update_project_agent_completion.sql
- database/src/main/resources/db/migrations/gendox-core/V20240117_160020__Add_moderation_project_agent.sql
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/ai/engine/services/cohere/aiengine/aiengine/CohereAiServiceAdapter.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/ai/engine/services/openai/aiengine/aiengine/OpenAiServiceAdapter.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/ai/engine/utils/constants/CohereConfig.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/ai/engine/utils/constants/GPTConfig.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/ai/engine/utils/constants/OpenAIADA2.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/AiModelRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/utils/SecurityUtils.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/utils/constants/QueryParamNames.java
related tickets: 165, 156, 166, 154, 109, 139
> Feature 165 fix bugs

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/UserController.java
> FIX ticket #97

- gendox-core-api/src/main/resources/application-prod.yml
> FIX ticket #181

- docker-compose.yml
- gendox-core-api/Dockerfile
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentSectionService.java
- copy aws credentials file into hetzner container
> FIX ticket #187

- database/src/main/resources/db/migrations/gendox-core/V20240226_122000__Integration_create_column.sql
- gendox-core-api/pom.xml
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/configuration/AWSConfig.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/configuration/IntegrationConfiguration.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/configuration/SQSConfig.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/converters/IntegrationConverter.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/model/Integration.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/model/dtos/IntegrationDTO.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/IntegrationRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/ProjectDocumentRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentContent.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DownloadService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/ProjectDocumentService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/SplitFileService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/GitIntegrationUpdateService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/IntegrationManager.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/S3BucketIntegrationUpdateService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/gitIntegration/FileSystemMultipartFile.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/s3BucketIntegration/ResourceMultipartFile.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/s3BucketIntegration/SQSListener.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/utils/constants/IntegrationTypesConstants.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/utils/constants/S3BucketIntegrationConstants.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSplitterProcessor.java
- gendox-core-api/src/main/resources/application-dev.yml
- gendox-core-api/src/main/resources/application-local.yml
- gendox-core-api/src/main/resources/application-prod.yml
- split SplitFileService to SplitFileService and DocumentContent
- update method deleteDocument in DocumentService
- create column queue_name
- integration
- IntegrationConverter
- IntegrationDTO
- V20240226_122000__Integration_create_column.sql
- IntegrationManager, update methods
- pom.xml, add SQS dependency
- ProjectDocumentService, create get and delete methods
- implements s3 bucket integration
- S3BucketIntegrationUpdateService
- SQSConfig
- SQSListener
- ResourceMultipartFile
> FIX ticket #186

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/ProjectController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/discord/utils/CommonCommandUtility.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/discord/utils/messages/ChatGendoxMessage.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/ProjectMemberRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/ProjectRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/UserOrganizationRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentSectionService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/OrganizationService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/ProjectMemberService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/UserOrganizationService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/s3BucketIntegration/SQSListener.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/utils/constants/AiModelConstants.java
- gendox-core-api/src/main/resources/application-dev.yml
- gendox-core-api/src/main/resources/application-local.yml
- gendox-core-api/src/main/resources/application-prod.yml
- Authentication checks for the Discord user.
> FIX ticket #196

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
- create the Get Document Sections Endpoint
> FIX ticket #210

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/AsyncController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/AsyncService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentSectionService.java
- gendox-frontend/src/configs/apiRequest.js
- gendox-frontend/src/views/gendox-components/document-sections-components/DocumentSectionsCard.js
- Implement Asynchronous Process Execution in API Endpoint
- Create front end split and training sections button
> FIX ticket #218

- gendox-frontend/src/pages/gendox/chat/index.js
- gendox-frontend/src/pages/gendox/home/index.js
- gendox-frontend/src/views/apps/chat/ChatContent.js
- gendox-frontend/src/views/apps/chat/ChatLog.js
- gendox-frontend/src/views/gendox-components/organization-settings/OrganizationSettingsCard.js
- gendox-frontend/src/views/gendox-components/project-settings-components/GeneralProjectSettings.js
- gendox-frontend/src/views/gendox-components/user-profile/UserViewLeft.js
- delete console.logs
- remove training icon button from home page
- create training icon in to project-settings
> FIX ticket #227

- database/pom.xml
- gendox-core-api/pom.xml
- Set version numbers in pom.xml
> Release 0.3

- gendox-frontend/src/@core/context/settingsContext.js
- gendox-frontend/src/@core/layouts/components/shared-components/UserDropdown.js
- gendox-frontend/src/@core/layouts/components/shared-components/footer/FooterContent.js
- gendox-frontend/src/configs/apiRequest.js
- gendox-frontend/src/configs/auth.js
- gendox-frontend/src/configs/themeConfig.js
- gendox-frontend/src/layouts/UserLayout.js
- gendox-frontend/src/layouts/components/vertical/AppBarContent.js
- gendox-frontend/src/navigation/vertical/VerticalNavButton.js
- gendox-frontend/src/pages/gendox/chat/index.js
- gendox-frontend/src/pages/gendox/home/index.js
- gendox-frontend/src/views/apps/chat/ChatContent.js
- gendox-frontend/src/views/apps/chat/SidebarLeft.js
- gendox-frontend/src/views/apps/chat/UserProfileRight.js
- gendox-frontend/src/views/gendox-components/OrganizationsDropdown.js
- gendox-frontend/src/views/gendox-components/home-page-components/project-buttons-components/ProjectButtons.js
- gendox-frontend/src/views/gendox-components/organization-settings/MembersOrganizationSettings.js
- gendox-frontend/src/views/gendox-components/organization-settings/OrganizationSettingsCard.js
- gendox-frontend/src/views/gendox-components/project-settings-components/AiAgentProjectSettings.js
- gendox-frontend/src/views/gendox-components/project-settings-components/MembersProjectSettings.js
- gendox-frontend/src/views/gendox-components/project-settings-components/ProjectSettingsCard.js
- gendox-frontend/src/views/gendox-components/user-profile/UserViewOverviewOrganizations.js
- implement all button to links
- implement url in chat (threadId)
- make buttons disable
> FIX ticket #257

- gendox-frontend/src/@core/components/auth/AuthGuard.js
- gendox-frontend/src/@core/layouts/components/shared-components/UserDropdown.js
- gendox-frontend/src/configs/auth.js
- gendox-frontend/src/configs/i18n.js
- gendox-frontend/src/context/AuthContext.js
- gendox-frontend/src/layouts/UserLayout.js
- gendox-frontend/src/layouts/components/vertical/AppBarContent.js
- gendox-frontend/src/navigation/vertical/VerticalNavButton.js
- gendox-frontend/src/store/apps/chat/index.js
- gendox-frontend/src/views/apps/chat/SidebarLeft.js
- gendox-frontend/src/views/apps/chat/UserProfileRight.js
- gendox-frontend/src/views/gendox-components/OrganizationsDropdown.js
- gendox-frontend/src/views/gendox-components/home-page-components/project-buttons-components/ProjectButtons.js
- gendox-frontend/src/views/gendox-components/organization-settings/MembersOrganizationSettings.js
- gendox-frontend/src/views/gendox-components/organization-settings/OrganizationSettingsCard.js
- gendox-frontend/src/views/gendox-components/project-settings-components/MembersProjectSettings.js
- gendox-frontend/src/views/gendox-components/project-settings-components/ProjectSettingsCard.js
- gendox-frontend/src/views/gendox-components/user-profile/UserViewLeft.js
FIX ticket #257
- Fix Double URL Opening in Chats
- Correct Message Sending Time in Chats
- Handle Token Expiry Gracefully
- Remove `component = a` from All Components
> Feature 257 fronend bugs and improvemebts

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/ProjectAgentController.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/model/dtos/criteria/ProjectAgentCriteria.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/MessageSectionRepository.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/specifications/ProjectAgentPredicates.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentSectionService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/MessageService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/ProjectAgentService.java
- Fix Bug, delete messageSection before sections deleted
- Create Project Agent Controller
- Implement get ProjectAgents by Criteria
> FIX ticket #281

- gendox-frontend/package.json
- gendox-frontend/src/configs/apiRequest.js
- gendox-frontend/src/configs/auth.js
- create environment variables for front end
> WIP #290 - create environment variables for front end

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/S3BucketIntegrationUpdateService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/integrations/s3BucketIntegration/SQSService.java
- gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSplitterWriter.java
- gendox-core-api/src/main/resources/application.yml
- SQS change batch-size for more messages
>    - SQS change batch-size

- gendox-core-api/src/main/resources/application-docker-local.yml
- gendox-core-api/src/main/resources/application-local.yml
- gendox-core-api/src/main/resources/application-prod.yml
>    - application hikari max pool

- gendox-frontend/src/store/apps/chat/index.js
- feature #319 metadata in new message
>  FIX  - feature #319 metadata in new message

- gendox-frontend/src/pages/gendox/document-instance/index.js
- gendox-frontend/src/views/apps/chat/chatLog-components/ChatLogInfo.js
- gendox-frontend/src/views/gendox-components/documents-components/SectionCard.js
- Implement scroll and highlight section from url
>  HOTFIX  - Implement scroll and highlight section

- gendox-frontend/src/@core/context/settingsContext.js
- gendox-frontend/src/@core/layouts/components/vertical/navigation/VerticalNavLink.js
- gendox-frontend/src/layouts/components/vertical/AppBarContent.js
- gendox-frontend/src/views/custom-components/global-search/GlobalSearch.js
- gendox-frontend/src/views/custom-components/global-search/GlobalSearchDialog.js
- gendox-frontend/src/views/pages/chat/conversation-components/ChatConversationInputSection.js
> FIX - feature-Global Search

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/ProjectService.java
- gendox-frontend/src/@core/layouts/components/vertical/navigation/VerticalNavLink.js
- gendox-frontend/src/@core/layouts/components/vertical/navigation/index.js
- gendox-frontend/src/utils/orderUtils.js
> FIX - create new project bugs

- database/pom.xml
- database/src/main/resources/db/migrations/gendox-core/V20250129_185310__Update_daily_usage_trigger_function.sql
- gendox-core-api/pom.xml
- Minor database migration update
> Release v0.8.1

- gendox-frontend/src/@core/context/settingsContext.js
- gendox-frontend/src/configs/themeConfig.js
- gendox-frontend/src/views/pages/organization-settings/general-components/InformationGeneralOrganizationSettings.js
- gendox-frontend/src/views/pages/project-settings-components/AiAgentProjectSettings.js
- gendox-frontend/src/views/pages/project-settings-components/GeneralProjectSettings.js
- ProvenAi enabled environment variable
> FIX - create environment variable ProvenAi enabled

- gendox-keycloak/themes/gendox/login/resources/css/login.css
- gendox-keycloak/themes/gendox/login/user-profile-commons.ftl
FIX - Keycloak register and update CSS
- Keycloak register and update CSS
> FIX - Keycloak register and update CSS

- gendox-core-api/src/main/java/dev/ctrlspace/gendox/authentication/JwtUserRegistrationFilter.java
- gendox-frontend/src/hooks/guards/useOrganizationProjectGuard.js
Fix: Cancel automatic organization creation for new users
- cancel created new organization where is a new user
> Fix: Cancel automatic organization creation for new users
